---
title: "Churn in Telecom Industry"
author: "Rahul Singh"
date: "1/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(corrplot)
library(ggplot2)
library(gridExtra)
library(ggthemes)
library(caret)
library(MASS)
library(randomForest)
library(party)
```


```{r}
churn <- read.csv('~/Desktop/IE MBD Term2/Marketing Intelligence/Churn Prediction in Telecom Industry/Unclean_Churn_Telecom.csv')
str(churn)
```

```{r}
#checking for na values
sapply(churn, function(x) sum(is.na(x)))
```

```{r}
#Remove rows with missing values
churn <- churn[complete.cases(churn), ]
```

```{r}
#We will change “No internet service” to “No” for six columns, they are: “OnlineSecurity”, “OnlineBackup”, “DeviceProtection”, “TechSupport”, “streamingTV”, “streamingMovies”.
cols_recode1 <- c(10:15)
for(i in 1:ncol(churn[,cols_recode1])) {
        churn[,cols_recode1][,i] <- as.factor(mapvalues
                                              (churn[,cols_recode1][,i], from =c("No internet service"),to=c("No")))
}
```

```{r}
#We will change “No phone service” to “No” for column “MultipleLines”
churn$MultipleLines <- as.factor(mapvalues(churn$MultipleLines, 
                                           from=c("No phone service"),
                                           to=c("No")))
```

```{r}
#Since the minimum tenure is 1 month and maximum tenure is 72 months, we can group them into five tenure groups: “0–12 Month”, “12–24 Month”, “24–48 Months”, “48–60 Month”, “> 60 Month”
min(churn$tenure); max(churn$tenure)
```

```{r}
group_tenure <- function(tenure){
    if (tenure >= 0 & tenure <= 12){
        return('0-12 Month')
    }else if(tenure > 12 & tenure <= 24){
        return('12-24 Month')
    }else if (tenure > 24 & tenure <= 48){
        return('24-48 Month')
    }else if (tenure > 48 & tenure <=60){
        return('48-60 Month')
    }else if (tenure > 60){
        return('> 60 Month')
    }
}
churn$tenure_group <- sapply(churn$tenure,group_tenure)
churn$tenure_group <- as.factor(churn$tenure_group)
```

```{r}
#Change the values in column “SeniorCitizen” from 0 or 1 to “No” or “Yes”.
churn$SeniorCitizen <- as.factor(mapvalues(churn$SeniorCitizen,
                                      from=c("0","1"),
                                      to=c("No", "Yes")))
```

```{r}
#customer ID and churn tenure are not needed in the dataset
churn<-churn[,c(-1,-22)]
```

```{r}
#repositioning churn column 
churn<-cbind(churn$Churn,churn)
#removing the duplicate last column
churn<-churn[,-21]
library(data.table)
setnames(churn, "churn$Churn", "churn_decision")
```


```{r}
# Write CSV in R
write.csv(churn, file = "~/Desktop/IE MBD Term2/Marketing Intelligence/Churn Prediction in Telecom Industry/Churn_new.csv",row.names=TRUE)
```

